services:
  wordpress:
    image: wordpress:latest
    hostname: wordpress
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      - default
    env_file:
      - .env
  db:
    platform: linux/x86_64
    image: mysql:latest
    hostname: db
    healthcheck:
      test: '/usr/bin/mysql -h127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 1000
    ports: 
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - default
volumes:
  db-volume:
